### ISSUE TITLE
PyPi disabled http access

### ISSUE THREAD

**Issue by clozinski** [zopefoundation/grokproject#10]
So I cloned grokproject on Debian linux.  Running in Python 2.7.9 virtual environment. 
I ran python bootstrap.py, but it died saying that  SSL is required. 

Attached are the full logs. 
Warm Regards
Chris
```
$python bootstrap.py 

Downloading http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg
Traceback (most recent call last):
  File "bootstrap.py", line 170, in <module>
    ez['use_setuptools'](**setup_args)
  File "<string>", line 103, in use_setuptools
  File "<string>", line 97, in do_download
  File "<string>", line 158, in download_setuptools
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: SSL is required
(virt279) lozinski@pythonlinks:~/code/development/grokproject$ 
```

**Comment by prsephton** [comment]
Pypi disabled http????  Oh my word! why would they do that???

**Comment by jamadden** [comment]
The short answer is because it's inherently unsafe. A longer explanation can be found in [Donald Stufft's message to distutils-sig](https://mail.python.org/pipermail/distutils-sig/2017-October/031712.html).

**Comment by prsephton** [comment]
Well, to suddenly decide HTTP is unsafe and just deprecate the entire protocol after 30 odd years of HTTP being quite fine for general use seems a bit extreme to me.  Do they have ANY IDEA of the number of projects they just broke?  Talk about unsafe!  PyPI as a repo has just classified itself as "unsafe" in my book.  There have been viruses less destructive than that singular decision to discard HTTP in favor of "security".
The term "Security" also includes the idea of "reliability", and I see the decision to pander to the "security agony aunts" and lose reliability in the process as particularly dumb.

**Comment by prsephton** [comment]
The version of bootstrap.py used in this project refers to http://peak.telecommunity.com/dist/ez_setup.py, which defines:

    DEFAULT_VERSION = "0.6c11"
    DEFAULT_URL     = "http://pypi.python.org/packages/%s/s/setuptools/" % sys.version[:3]

Of course, its that **http:** that is causing the problem..

Who knows who is in charge of ez_setup at  http://peak.telecommunity.com???

This means we will probably have to look at a newer bootstrap.py.  **

Since grokproject is a project which builds a project, the project that it builds also has a bootstrap.py which suffers from the same malady.

Using a later bootstrap.py also means a later buildout, and there are a pile of differences and implications to work through.

We are very specifically pinning versions of packages in grokproject, and those pinned versions may conflict with newer packages now required to support the deprecation of HTTP://pypy.python.org.

Nevertheless, as I find the time I will see what can be done about adapting things.  (If it turns out to be too much of a mission, I'll just go with npm/node.js/react instead :-)

**Although the recommendation these days, as I understand it to be is to just use buildout directly, I personally prefer using bootstrap.py.  Its nice to be able to start a buildout project from nothing except bootstrap.py and buildout.cfg.

**Comment by clozinski** [comment]
Thank you for explaining the problem. I would think that I could just copy 
http://peak.telecommunity.com/dist/ez_setup.py
to my local file system.  change the line
setuptools_source = 'https://peak.telecommunity.com/dist/ez_setup.py'
to be
setuptools_source = 'file:./ez_setup.py'

edit the file ./ex_setup.py to include the https url
```
                                             v
DEFAULT_URL     = "https://pypi.python.org/packages/%s/s/setuptools/" % sys.version[:3]
                                             ^
```
And all would e fine.  Is that correct?  What am I missing?

Warm Regards
Chris

**Comment by prsephton** [comment]
It's a bit cludgy, and it is possible that what you say would partly fix the problem.  But don't forget that grokproject makes a project, and that also has a bootstrap.py that must be altered.  Also, any references to http://pypi.. in setup.py must be changed.  Any projects created by grokproject will remain broken, even after we fix grokproject.

I personally have a whole bunch of projects that were created by grokproject in the past which are all suddenly no longer able to access http://pypi... for updates.  It's irritating to be in a position where older installations just don't work anymore.  

Remember that not all devs care about WHY it broke, just THAT it broke and have no interest in wasting time fiddling with editing files to try to make it work.  If it stops working many will just move on to using more stable/secure platforms, and I, for one, don't blame them.

The right approach I think, is to make the shift to using buildout v2.  Perhaps v1.5.5 of grokproject is the place to do it.

Some time ago, setuptools was altered to no longer support in-place upgrading of itself.  Bootstrap.py was pinned at that point to use v33.1.1 of setuptools, being the last version to support in-place upgrades.  So we know that there will be no new releases of bootstrap.py since newer setuptools no longer supports what bootstrap does.

We have also had a buildout upgrade from v1 series to v2 series, and a few things have dropped by the wayside.  In particular, z3c.recipe.script no longer works, and zc.recipe.egg must be used instead; unfortunately the interpreter scripts produced by zc.recipe.egg are very much inferior to the ones z3c.recipe.script produced.  Also the z3c.recipe.i18n has dependencies that break for buildout v2 in conjunction with older grokproject dependencies.

There are some ways to address the limitations in the interpreter that zc.recipe.egg creates, and we can with a bit of cumbersome coding get a 'python-console' interpreter that can serve inside an IDE.

**Comment by clozinski** [comment]
So what are Pyramid and Plone doing about these problem?
Good to follow in their footsteps.  

From 
https://github.com/Pylons/pyramid-cookiecutter-alchemy
It looks like Pyramid is using standard setuptools with no buidout.cfg file.   Is that true?

As for Plone
https://github.com/plone/buildout.coredev

Looks like they are still using buildout.  Click open their setup.py
Lots of references to https. 

So I gave it a shot
removed the old version of bootstrap.py
$wget https://raw.githubusercontent.com/plone/buildout.coredev/5.1/bootstrap.py
$python bootstrap.py
$bin/buildout

SIgh.  Does not work. 

 [versions] constraint on setuptools: 0.6c11
  Requirement of zc.recipe.egg==1.3.2: setuptools
  Requirement of zc.buildout>=1.5.0: setuptools>=8.0
While:
  Installing.
  Getting section grokproject.
  Initializing section grokproject.
  Installing recipe zc.recipe.egg.
Error: The requirement ('setuptools>=8.0') is not allowed by your [versions] constraint (0.6c11)

I generally think that the Plone community is large enough to get this all working.  
But I am not even quite sure what the different versions of zc.recipe.egg and setuptools do.   Somehow it all
just works to build my projects.  And so I do not have good judgement in which direction to proceed. What do you recommend? Am I on the right track?

**Comment by prsephton** [comment]
I have made the changes for grokproject to use buildout 2 and setuptools 33.1.1.  Right now Travis is barfing (again) and I need to double check everything.    In the meanwhile, you can clone from my personal github repo  at github.com/prsephton to check it out.  I still need to come up with something reasonable to update existing grokproject installations.

**Comment by clozinski** [comment]
Wpw.  That was fast.  I could not have done it that fast, but at least I can help by testing it. 

So I deleted my grokproject.  Git cloned the prsephton version.  
python bootstrap.py, and then buildout. 
It complained about a missing ScriptBase
>ImportError: cannot import name ScriptBase
Below is my screen capture.  



(virt279) lozinski@pythonlinks:~/code/development/grokproject$ cd ..
(virt279) lozinski@pythonlinks:~/code/development$ rm -rf grokproject
(virt279) lozinski@pythonlinks:~/code/development$ !git 
git clone https://github.com/prsephton/grokproject 
Cloning into 'grokproject'...
remote: Counting objects: 3103, done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 3103 (delta 49), reused 63 (delta 18), pack-reused 3009
Receiving objects: 100% (3103/3103), 1.54 MiB | 2.25 MiB/s, done.
Resolving deltas: 100% (1390/1390), done.
Checking connectivity... done.
(virt279) lozinski@pythonlinks:~/code/development$ cd grokproject/
(virt279) lozinski@pythonlinks:~/code/development/grokproject$ python bootstrap.py 
ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip
Extracting in /tmp/tmpmp81ab
Now working in /tmp/tmpmp81ab/setuptools-33.1.1
Building a Setuptools egg in /tmp/bootstrap-rUIQ71
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/bootstrap-rUIQ71/setuptools-33.1.1-py2.7.egg
no previously-included directories found matching 'doc'
no previously-included directories found matching 'old-tutorial'
Creating directory '/home/lozinski/code/development/grokproject/bin'.
Creating directory '/home/lozinski/code/development/grokproject/parts'.
Creating directory '/home/lozinski/code/development/grokproject/develop-eggs'.
Generated script '/home/lozinski/code/development/grokproject/bin/buildout'.
(virt279) lozinski@pythonlinks:~/code/development/grokproject$ bin/buildout
Develop: '/home/lozinski/code/development/grokproject/.'
While:
  Installing.
  Getting section test.
  Initializing section test.
  Loading zc.buildout recipe entry zc.recipe.testrunner:default.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/lozinski/.buildout/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/lozinski/.buildout/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 680, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/lozinski/.buildout/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1274, in __getitem__
    options._initialize()
  File "/home/lozinski/.buildout/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1382, in _initialize
    self.initialize()
  File "/home/lozinski/.buildout/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1388, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/lozinski/.buildout/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1343, in _install_and_load
    req.project_name, group, entry)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/lozinski/.buildout/eggs/zc.recipe.testrunner-1.4.0-py2.7.egg/zc/recipe/testrunner/__init__.py", line 22, in <module>
    import z3c.recipe.scripts.scripts
  File "/home/lozinski/.buildout/eggs/z3c.recipe.scripts-1.0.1-py2.7.egg/z3c/recipe/scripts/__init__.py", line 1, in <module>
    from z3c.recipe.scripts.scripts import Scripts, Interpreter
  File "/home/lozinski/.buildout/eggs/z3c.recipe.scripts-1.0.1-py2.7.egg/z3c/recipe/scripts/scripts.py", line 19, in <module>
    from zc.recipe.egg.egg import ScriptBase
ImportError: cannot import name ScriptBase
(virt279) lozinski@pythonlinks:~/code/development/grokproject$

**Comment by prsephton** [comment]
Thanks Chris.  I will look at it soon!

**Comment by clozinski** [comment]
Well the newest release of grokproject works great. 
Thank you enormously Paul.

**Comment by prsephton** [comment]
You are welcome. Tavis still barfs because of a buildout bug. Trying to
think of ways to work around it.

On 16 Nov 2017 15:28, "Christopher Lozinski" <notifications@github.com>
wrote:

Well the newest release of grokproject works great.
Thank you enormously Paul.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/zopefoundation/grokproject/issues/10#issuecomment-344922361>,
or mute the thread

**Comment by clozinski** [comment]
And I integrated grokproject into my application, and that now starts up fine on my dev server. 

I should mention that  there was some problem, but when I cleared out my dlcache, extends and eggs directories, everything then worked fine.

**Comment by prsephton** [comment]
Travis works ok, with a few workarounds.  Tests run ok if you use 'shorttests' - only on the second run; this is due to the fact that buildouts output is significantly different from the previous buildout, and there's a buildout bug which erroneously reports a version conflict for eggs that clash with globally installed eggs.

Glad to hear things are working fo @clozinski.

I will be putting some work into cleaning up the tests soon, so that they run reliably.

Once this patch is merged we can do a release to PyPI, which should fix the problem with missing changes.txt as well as the HTTPS vs. HTTP issues.

**Comment by prsephton** [comment]
This issue has been solved by latest PR
